


services:
  db:
    image: postgres:15
    container_name: oursay-postgres
    environment:
      POSTGRES_USER: oursay
      POSTGRES_PASSWORD: RILEY2015
      POSTGRES_DB: oursaydb
    ports:
      - "5431:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: ./backend
    container_name: oursay-backend
    depends_on:
      - db
    env_file:
      - .env
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: oursay
      DB_PASSWORD: RILEY2015
      DB_NAME: oursaydb
      JWT_SECRET: super_secret_dev_key
      PASSWORD_SALT: dev_salt_change_me
      AWS_REGION: eu-west-1
      AWS_COGNITO_IDENTITY_POOL_ID: eu-west-1:0819e9c0-e9e6-448f-8969-ccb836debbce
      AWS_ACCESS_KEY_ID: AKIAVDLVOSE5HKCSMB7O
      AWS_SECRET_ACCESS_KEY: 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
    ports:
      - "3000:3000"

volumes:
  postgres_data: