


services:
  db:
    image: postgres:15
    container_name: oursay-postgres
    environment:
      POSTGRES_USER: oursay
      POSTGRES_PASSWORD: RILEY2015
      POSTGRES_DB: oursaydb
    ports:
      - "5431:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: ./backend
    container_name: oursay-backend
    depends_on:
      - db
    env_file:
      - .env
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: oursay
      DB_PASSWORD: RILEY2015
      DB_NAME: oursaydb
      JWT_SECRET: ${JWT_SECRET}
      PASSWORD_SALT: ${PASSWORD_SALT}
      AWS_REGION: ${AWS_REGION}
      AWS_COGNITO_IDENTITY_POOL_ID: ${AWS_COGNITO_IDENTITY_POOL_ID}
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
    ports:
      - "3000:3000"

volumes:
  postgres_data: